INSERT INTO USER (USERNAME, PASSWORD) VALUES ('fulga', 'P1dt5561Q');

INSERT INTO ALBUM (USER_ID, ALBUM_NAME, CREATION_DATE) VALUES((SELECT USER_ID FROM USER WHERE USERNAME = 'fulga'), 'Poze', CURRENT_TIMESTAMP());

/*INSERT INTO PHOTO (ALBUM_ID, NAME, UPLOAD_DATE, PHOTO_DATA) VALUES ((SELECT ALBUM_ID FROM ALBUM WHERE ALBUM_NAME = 'Poze'), 'poza 1', CURRENT_TIMESTAMP(),FILE_READ('classpath:/pictures/p1.jpg',NULL));
INSERT INTO PHOTO (ALBUM_ID, NAME, UPLOAD_DATE, PHOTO_DATA) VALUES ((SELECT ALBUM_ID FROM ALBUM WHERE ALBUM_NAME = 'Poze'), 'poza 2', CURRENT_TIMESTAMP(),FILE_READ('classpath:/pictures/p2.png',NULL));*/
