CREATE TABLE USER (
  USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USERNAME VARCHAR(200) NOT NULL,
  PASSWORD VARCHAR(200) NOT NULL,
);

CREATE TABLE ALBUM (
  ALBUM_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  USER_ID BIGINT,
  ALBUM_NAME VARCHAR(200) NOT NULL,
  CREATION_DATE DATE
);


CREATE TABLE PHOTO (
  PHOTO_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ALBUM_ID BIGINT,
  NAME VARCHAR(200) NOT NULL,
  UPLOAD_DATE DATE,
  PHOTO_DATA IMAGE
);